[build]
builder = "NIXPACKS"
buildCommand = "composer install --optimize-autoloader --no-dev && npm install && npm run build && php artisan view:cache"

[deploy]
# Menjalankan symlink storage dan migrasi database sebelum aplikasi go-live
releaseCommand = "php artisan storage:link ; php artisan migrate --force"
